apiVersion: v1
kind: Secret
metadata:
  name: ad-secrets
  namespace: default
type: Opaque
data:
  AdConfig__UsuarioAdmin: "U2lzdGVtYXM="
  AdConfig__SenhaAdmin: "QmFyaUAyMDIx"
  AdConfig__AppLogin: "U2lzdGVtYXM="
  AdConfig__AppSenha: "QmFyaUAyMDIx"