apiVersion: v1
kind: Secret
metadata:
  name: ad-secrets
  namespace: default
type: Opaque
data:
  # Credenciais Admin AD (Para operações de escrita)
  AdConfig__UsuarioAdmin: "U2lzdGVtYXM="
  AdConfig__SenhaAdmin: "QmFyaUAyMDIx"  
  
  AdConfig__MasterUser: "U2lzdGVtYXM="
  AdConfig__MasterPass: "QmFyaUAyMDIx"